import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><nav style={{
  display: "flex",
  gap: 12,
  padding: 12,
  borderBottom: "1px solid #ddd"
}}>
  <a href="/calendar">📅 カレンダー</a>
  <a href="/todo">✅ ToDo</a>
</nav>
        {children}
      </body>
    </html>
  );
}
